connection:
  device: "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_BG03FM3C-if00-port0"
  baud: 921600

safety:
  bench_read_only: true
  allow_arm: false
  allow_bench_arm_test: true
  allow_takeoff: false

control:
  command_interval: 0.10

velocity:
  forward: 0.3
  backward: -0.3
  right: 0.3
  left: -0.3
  up: -0.2
  down: 0.2
  yaw_rate: 10

camera:
  index: 0
  width: 480
  height: 360
  fps: 30

gesture:
  history_size: 9
  min_votes: 6
  no_gesture_timeout: 0.30
  command_cooldown: 0.25
